version: '3.8'

services:
  db:
    image: mysql:8.3.0
    container_name: mysql830
    ports:
      - "33306:3306"
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    volumes:
      - ./db/mysql/conf.d:/etc/mysql/conf.d
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
    env_file:
      - ./backend/.env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_HOST=${MYSQL_HOST}
      - TZ=Asia/Seoul


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: ysolarh/backend:latest
    container_name: backend
    env_file:
      - ./backend/.env
    environment:
      - DB_HOST=${MYSQL_HOST}
    volumes:
      - ./backend:/backend
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - db

